name: Build Affine IO-Mai

on:
  push:
    branches: [ main, master ]
    paths:
      - 'mai2io/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'mai2io/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        working-directory: mai2io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make

      - name: Build Mai DLL
        run: |
          gcc -m64 -shared mai2io.c config.c serial.c dprintf.c -o mai2io_affine.dll -lsetupapi

      - name: Build Mai Test Program
        run: |
          gcc -m64 test.c serial.c dprintf.c -o curva_test.exe -lsetupapi

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mai2io_affine-dll
          path: mai2io/mai2io_affine.dll

      - name: Upload Test Program Artifact
        uses: actions/upload-artifact@v4
        with:
          name: curva_test-exe
          path: mai2io/curva_test.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mai2io/mai2io_affine.dll
            mai2io/curva_test.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
