name: Build Affine IO-Mai

on:
  push:
    branches: [ main, master ]
    tags: [ '*' ]
  pull_request:
    branches: [ main, master ]
    paths:
      - 'mai2io/**'
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      run_build: ${{ steps.final.outputs.run_build }}
    steps:
      - id: pre
        run: |
          if [ "${{ github.event_name }}" = "release" ] || [[ "${{ github.ref }}" == refs/tags/* ]] || [ "${{ github.event_name }}" = "workflow_dispatch" ] || [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "run_build=true" >> "$GITHUB_OUTPUT"
          else
            echo "run_build=" >> "$GITHUB_OUTPUT"
          fi
      - if: steps.pre.outputs.run_build == ''
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - if: steps.pre.outputs.run_build == ''
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            mai2io:
              - 'mai2io/**'
      - id: final
        run: |
          if [ -n "${{ steps.pre.outputs.run_build }}" ]; then
            echo "run_build=true" >> "$GITHUB_OUTPUT"
          else
            if [ "${{ steps.filter.outputs.mai2io }}" = "true" ]; then
              echo "run_build=true" >> "$GITHUB_OUTPUT"
            else
              echo "run_build=false" >> "$GITHUB_OUTPUT"
            fi
          fi

  build:
    runs-on: windows-latest
    needs: [changes]
    if: needs.changes.outputs.run_build == 'true'
    defaults:
      run:
        shell: msys2 {0}
        working-directory: mai2io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-libusb
            mingw-w64-x86_64-pkg-config

      - name: Build Mai DLL
        run: |
          gcc -m64 -shared mai2io.c config.c serial.c dprintf.c -o mai2io_affine.dll -lsetupapi

      - name: Build Mai Test Program
        run: |
          gcc -m64 test.c serial.c dprintf.c dfu.c -lsetupapi -luser32 -lkernel32 -Wl,-Bstatic $(pkg-config --cflags --libs libusb-1.0) -Wl,-Bdynamic -o curva_test.exe

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mai2io_affine-dll
          path: mai2io/mai2io_affine.dll

      - name: Upload Test Program Artifact
        uses: actions/upload-artifact@v4
        with:
          name: curva_test-exe
          path: mai2io/curva_test.exe

      - name: Create Release (for tag push only)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mai2io/mai2io_affine.dll
            mai2io/curva_test.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install AWS CLI
        if: github.event_name == 'release' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
        shell: powershell
        run: |
          choco install awscli -y
          aws --version

      - name: Upload DLL to Cloudflare R2 (tag subdir + latest.json)
        if: github.event_name == 'release' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
        shell: powershell
        working-directory: mai2io
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
        run: |
          $tag = if ("${{ github.event_name }}" -eq "release") { "${{ github.event.release.tag_name }}" } else { "${{ github.ref_name }}" }

          $base = "s3://$env:R2_BUCKET/ruminasu/public/scripts/affine/mai2io"
          $dest = "$base/$tag/"

          aws s3 cp "mai2io_affine.dll" "$dest" `
            --endpoint-url "$env:R2_ENDPOINT" `
            --cache-control "public,max-age=31536000,immutable"

          $hash = (Get-FileHash "mai2io_affine.dll" -Algorithm SHA256).Hash.ToLower()
          $size = (Get-Item "mai2io_affine.dll").Length
          $manifestObj = @{
            version     = $tag
            file        = "mai2io_affine.dll"
            size        = $size
            sha256      = $hash
            path        = "/ruminasu/public/scripts/affine/mai2io/$tag/mai2io_affine.dll"
            uploaded_at = (Get-Date).ToString("s")
          }
          $manifestJson = $manifestObj | ConvertTo-Json -Compress
          $manifestJson | Out-File -Encoding utf8 "manifest.json"
          aws s3 cp "manifest.json" "$dest" `
            --endpoint-url "$env:R2_ENDPOINT" `
            --cache-control "public,max-age=31536000,immutable"

          $manifestJson | Out-File -Encoding utf8 "latest.json"
          aws s3 cp "latest.json" "$base/latest.json" `
            --endpoint-url "$env:R2_ENDPOINT" `
            --cache-control "public,max-age=60"
